name: Publish tag release images

on:
  push:
    tags:
      [ v* ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/ansible-playbook:${{ github.GITHUB_REF_NAME }}
            ghcr.io/${{ github.repository_owner }}/ansible-playbook:${{ github.GITHUB_REF_NAME }}

      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ganawa
          slug: ganawa/ansible-playbook
          pass: ${{ secrets.DOCKER_HUB_PASS }}
          description: true
